### ISSUE TITLE
plugin: 'trigger' failed to initialize

### ISSUE THREAD

**Issue by JamieKG** [barneygale/mark2#101]
I get the following error when starting a server instance with the triggers enabled
http://pastebin.com/WUanC8g4

**Comment by JamieKG** [comment]
my bad config error

**Comment by crubinsson** [comment]
I have started getting the same problem: http://pastebin.com/U7QZaGk5
Don't really know what i did when it stopped working... >.<

Could you update the thread with what the config error was?

Thanks
Chris

**Comment by JamieKG** [comment]
Yes in your mark2.properties change
plugin.trigger.filename=triggers.txt
for
plugin.trigger.path=triggers.txt

Thanks JamieKG

**Comment by crubinsson** [comment]
Oh, the variables changed in the config of course... Thanks!
