### ISSUE TITLE
Allow customisation of unknown command based monitor pattern?

### ISSUE THREAD

**Issue by ghost** [barneygale/mark2#105]
Would it be possible to allow us to customize the pattern for the unknown command check in monitor.py? The current pattern causes mark2 to restart our server due to having a different response to a unknown command.

**Comment by edk0** [comment]
We can definitely add that.

In the meantime, you can set something like:

``` properties
plugin.monitor.crash-enabled=false
```

**Comment by ghost** [comment]
Thanks! Will use the workaround till then.

**Comment by gsand** [comment]
Unknown Command Message regex. (In my case, it's: Ooops, that command is invalid)
`
plugin.monitor.crash-unknown-cmd-message=Ooops*
`
Crash Detection Command (only modify if there is a command that messes with it.)
`
plugin.monitor.crash-check-command=
`

**Comment by gsand** [comment]
@edk, @barneygale or @TehRainbowGuy 

Please close this issue.
