### ISSUE TITLE
triggers help

### ISSUE THREAD

**Issue by trentech** [barneygale/mark2#108]
I need help with triggers. I'm not 100% i know what they do. I assume for example someone says a specific word and a response is sent to that player. Problem is when testing this theory nothing happens. Little help.

**Comment by barneygale** [comment]
Aye. It's a factoid database, e.g. a player might write "!irc" in chat, and the server will "/say Our IRC channel is #xyz ...".

To make it work you need a file called "triggers.txt" in the same directory as your server jar.

One common reason it doesn't work is if you use plugins which modify the console chat format. It's expecting a simple "<username> message here" format. If you use something different, could you please paste a portion of your server log showing some chat lines?
