### ISSUE TITLE
Unable to use JMX profiling flags

### ISSUE THREAD

**Issue by sawine** [barneygale/mark2#134]
Hi,

I don't know if I just got the syntax wrong, but I tried in 3 different ways and I'm unable to get the JVM to start with those args:

java.cli-extra=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx
java.cli-extra=-Dcom.sun.management.jmxremote.port=xxxxx
java.cli-extra=-Dcom.sun.management.jmxremote.ssl=false 

Tried like this too:

java.cli.D.java.rmi.server.hostname=xxx.xxx.xxx.xxx
java.cli.D.com.sun.management.jmxremote.port=xxxxx
java.cli.D.com.sun.management.jmxremote.ssl=false

And like this....

-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx
-Dcom.sun.management.jmxremote.port=xxxxx
-Dcom.sun.management.jmxremote.ssl=false 

Regards

**Comment by gsand** [comment]
This is the correct syntax:

```
java.cli.D.java.rmi.server.hostname=xxx.xxx.xxx.xxx
java.cli.D.com.sun.management.jmxremote.port=xxxxx
java.cli.D.com.sun.management.jmxremote.ssl=false
```

Might be a bug.

possible solution: try escaping the periods in the hostname?

The following works:

```
java.cli.D.java.rmi.server.hostname=xxx\.xxx\.xxx\.xxx
java.cli.D.com.sun.management.jmxremote.port=xxxxx
java.cli.D.com.sun.management.jmxremote.ssl=false
```

**Comment by sawine** [comment]
Escaping periods fixed it

Thanks! :)
