### ISSUE TITLE
Unable to Config Mark2

### ISSUE THREAD

**Issue by badnatho** [barneygale/mark2#141]
Since my last issue went cold. I'm starting a new one that is properly titled etc.

I cannot config my mark2 install. (after reinstalling everything that is required)

```
[root@ks4000277 mark2]# sudo mark2 config
Traceback (most recent call last):
  File "/usr/bin/mark2", line 9, in <module>
    load_entry_point('mark2==0.1.4.3', 'console_scripts', 'mark2')()
  File "/usr/mark2/mk2/launcher.py", line 605, in main
    command.start()
  File "/usr/mark2/mk2/launcher.py", line 126, in start
    self.run()
  File "/usr/mark2/mk2/launcher.py", line 479, in run
    subprocess.call([editor, path_tmp])
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@ks4000277 mark2]# 
```

Its seems that others have had this issue (look at the dates):
http://pastebin.com/T5VEiW6U
http://pastebin.com/UgGU3hNT
http://pastebin.com/hDtPQ3e8

I cannot find where they have posted this to but when I googled my issue it came up with just these 3 links on google.

Please Help since I would like this resolved as quickly as possible.

Running CentOs 6.4 with Python [2.6,2.7,3.3] and everything required for Mark2

**Comment by crawfonw** [comment]
This is the same problem as in issue #115. It was fixed in this pending commit: https://github.com/skovhus/mark2/commit/3cc16da597675013bd4482b33d21de480fe3dbfa. Just edit your `launcher.py` file as in the commit so it opens in your favorite editor.

**Comment by hakusaro** [comment]
Alternatively, you can just use the following (assuming you have nano installed):

``` bash
export EDITOR=nano
```

That should work until the bug is fixed here.
