### ISSUE TITLE
Mark2 not working: config fails

### ISSUE THREAD

**Issue by Trikolon** [barneygale/mark2#160]
When I try to get mark2 running on my debian-server it fails. The command "mark2 config" gives me the following errors: http://pastebin.com/ffPhWYTJ

I did, according to this tutorial, move back to an old version, which seems to be stable: https://gist.github.com/vemacs/5663144#setting-up-mark2
This seems to lack color-support though: http://puu.sh/a6jII/c7579e8de5.png

My setup:
Debian Wheezy
Python 2.7.3
All packages installed according to the INSTALL.md file.

**Comment by ghost** [comment]
Getting the same error on CentOS 6 running python 2.6

**Comment by ykondrashyn** [comment]
Same here. Debian Wheezy, Python 2.6.6

**Comment by gsand** [comment]
sudo nano /etc/mark2/mark2.properties

enter space

ctrl+x and save

then create a mark2.properties config in the same directory as the server.
