### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by IamGalaxias** [barneygale/mark2#165]
Hello,

I recently stopped BungeeCord by typing 'end'. Everything worked just fine, but for some reason, I was suddenly attached to the screen of another user!

This is a security problem, allowing anyone to attach to somebody else's screens.

**Comment by edk0** [comment]
duplicated at gsand/mark2#16

**Comment by IamGalaxias** [comment]
Yes, I was not sure where to put it. Sorry.
