### ISSUE TITLE
Provide a way of copying text from console

### ISSUE THREAD

**Issue by barneygale** [barneygale/mark2#26]
This may be a feature of the client if possible, or a simplified client could be run as `mark2 follow`

**Comment by barneygale** [comment]
Holding 'shift' while selecting works, but brings the terminal line-art with it.

I suggest we implement a "full screen" mode that can be toggled with a keyboard shortcut. This would just show server output using all but the bottom row, which would be the prompt.

**Comment by edk0** [comment]
Holding ctrl-shift for block selection should work
