### ISSUE TITLE
~restart command? not working as in the scripts.txt samples?

### ISSUE THREAD

**Issue by SupaYoshi** [barneygale/mark2#32]
Hello, i tried the restart sample as it is in the samples of mark2 but ~restart wont work.

Can someone please explain why it isnt?

Thanks!

Would like it for the custom reboot message ;)

http://pastebin.com/5wZxwziL

**Comment by barneygale** [comment]
You're trying to run ~restart at 1:46am every day?

**Comment by barneygale** [comment]
Just saw your comments in #mcdevs (I'm Stormx2 on freenode fyi). 

You can run restart from console - run `mark2 attach`, then type "~restart" into the box at the bottom. See ~help for a list of commands.

From shell you can issue a ~restart with `mark2 send ~restart`

**Comment by SupaYoshi** [comment]
So how would I setup a autoreboot? This answer is nice.. but this still doesnt help me with scripts.txt

I can do ~ to execute a mark2 command it says, but actually I cannot? Since ~restart won't work only when attached. So How can i restart?

Help!

**Comment by barneygale** [comment]
Set up an autoreboot in scripts.txt. Specify a timespec for how often you want it to occur, e.g.

```
0   */2 *   *   *   ~restart
```

Will restart every 2 hours. [see here](http://www.adminschoice.com/crontab-quick-reference) for more info on crontab

**Comment by SupaYoshi** [comment]
Hey, i tried as you said on IRC.

This worked:
    \* \* \* \* \* /say foo

;) when i type restart from mark2 attach, it says: 2013-02-24 13:36:55 | Startup script 'start.bat' does not exist!

When doing ~restart from mark2 attach it works.

Maybe that has something to do with it?
- \* \* \* \* ~restart wont work either btw ;)

haha. help?

**Comment by barneygale** [comment]
> when i type restart from mark2 attach, it says: 2013-02-24 13:36:55 | Startup script 'start.bat' does not exist!

All mark2 console commands begin with a tilde. By typing "restart" into console, you're running **the minecraft command `restart`**. This isn't defined in vanilla minecraft so I'd imagine you have a bukkit plugin that hooks `restart`.

> When doing ~restart from mark2 attach it works.

Good

> - \* \* \* \* ~restart wont work either btw ;)

Weird that `say` works but `~restart` doesn't. I'll try again to reproduce and get back to you.

**Comment by barneygale** [comment]
I can't reproduce this. Could you
1. Make sure you're running very latest mark2
2. Send me your 'config/mark2.properties', and the 'mark2.properties' in your server directory if you have one defined
3. Send me your 'scripts.txt'
4. Send me '/tmp/mark2/nameofyourserver.log'

You could use http://gist.github.com to paste em.

**Comment by barneygale** [comment]
SupaYoshi, is this still not working for you?

**Comment by barneygale** [comment]
Please open another issue if you're still experiencing this in current mark2.

**Comment by SupaYoshi** [comment]
Hey barney, sorry for the late response. I was able to fix it, eventually it just worked ;) I been bsuy with everything and nothing lately. Wil be back soon askin new questions. This was solved for me the way you told me it. and it works.
