### ISSUE TITLE
client: configurable modes for showing/hiding console lines

### ISSUE THREAD

**Issue by barneygale** [barneygale/mark2#46]
mark2rc should add two configuration sections:
1. A section for defining named regexes
2. A section for defining named filters, something like `filter.chat=show:join,part,chat` or `filter.nofactions=hide:factions`

Filters can be a blacklist or a whitelist. 

'join', 'quit' and 'chat' should be loaded from mark2.props - the best way to do this I think is to add something to user_server and user_client to send em over on attach. 

In the client, the user should be able to pick which filter is active (if any). See #45 for UI.

**Comment by edk0** [comment]
I'm calling this finished. Adding the UI is part of #45.
