### ISSUE TITLE
Encoding error in attach

### ISSUE THREAD

**Issue by vemacs** [barneygale/mark2#54]
Simply put, I have setup [mark2](https://github.com/mcdevs/mark2), and I can `mark2 start` and `mark2 stop` perfectly fine.

However, when I run `mark2 attach`, I get [this error](http://pastie.org/pastes/7469714/text).

What's strange is I can see all the startup and shutdown console perfectly fine.

This seems like a strange issue, and I was wondering if anybody had any solutions?

Thanks in advance. I'm running [MCPC-Plus-Legacy](http://ci.md-5.net/job/MCPC-Plus-Legacy/).

Here's my mark2.properties: 

```
java.cli.X.ms=1600M
java.cli.X.mx=1600M
mark2.jar-path=mcpc-plus.jar
java.user=nullblock
java.cli-extra=-server
java.cli.D.jline.terminal=jline.UnsupportedTerminal
plugins.irc.enabled=false
```

Here's the output of locale:

```
nullblock@ftb:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by edk0** [comment]
ed62708 should have fixed this issue (worked for me when I set my locale to POSIX)
