### ISSUE TITLE
Could not create the Java virtual machine.

### ISSUE THREAD

**Issue by Brottweiler** [barneygale/mark2#57]
Hello. I have tried for so long now to get mark2 to start my server, but it just refuses.
I have no idea what to do. Everything should be correct. I can only assume mark2 tried to launch a java that doesn't exist or something. Please help!

I run "mark2 start" and I get this: 
$ mark2 start
2013-04-15 19:52:34 # mark2 starting...
2013-04-15 19:52:34 # starting minecraft server
2013-04-15 19:52:34 | [???] Could not create the Java virtual machine.
2013-04-15 19:52:34 # fatal error: A process has ended with a probable error condition: process ended with exit code 1.
2013-04-15 19:52:34 # mark2 stopped.

I have java installed;
$ dpkg --get-selections | grep jdk
openjdk-6-jre                   install
openjdk-6-jre-headless              install
openjdk-6-jre-lib               install
openjdk-7-jdk                   install
openjdk-7-jre                   install
openjdk-7-jre-headless              install
openjdk-7-jre-lib               install
$ dpkg --get-selections | grep jre
icedtea-6-jre-cacao             install
icedtea-6-jre-jamvm             install
icedtea-7-jre-jamvm             install
openjdk-6-jre                   install
openjdk-6-jre-headless              install
openjdk-6-jre-lib               install
openjdk-7-jre                   install
openjdk-7-jre-headless              install
openjdk-7-jre-lib               install

**Comment by vemacs** [comment]
Are you running an openVZ VPS?

**Comment by Brottweiler** [comment]
No, it is a dedicated server.

**Comment by vemacs** [comment]
@Brottweiler Can you start it directly from the command line?

```
java -Xms2G -Xmx2G -server -jar <server jar name>.jar
```

That way, you can rule out if it's actually mark2.

**Comment by Brottweiler** [comment]
Yes, without any issues. It starts like normal.

**Comment by barneygale** [comment]
Could you pastebin/whatever your config file, specifically things beginning with "java."?

**Comment by Brottweiler** [comment]
http://pastie.org/private/o2tv2gvt1montihdjq4fxa
It's pretty much default. And yes, I have tried to launch craftbukkit-beta.jar instead of spigot, same thing.

**Comment by barneygale** [comment]
Sorted via IRC (too much memory allocated). e62435f lets us actually see java's complaint.

**Comment by Brottweiler** [comment]
The original issue was not that I had too much memory allocated. 
This was what fixed my issue: https://github.com/mcdevs/mark2/compare/612fb1aae5bb...1b515e9e8816
When that was fixed I got another error, which was just due to my config beeing set up to allocate 3G RAM when I only had 2G. Changed that, and I can run the server!

Thanks for the support!

**Comment by edk0** [comment]
That didn't fix the error, it just showed you the error message java was making the whole time :)

**Comment by Brottweiler** [comment]
Oh, well there you go! Thanks!
