### ISSUE TITLE
Error when attaching

### ISSUE THREAD

**Issue by lwatsondev** [barneygale/mark2#65]
getting an encoding error when attaching with mark2, on Debian.

I followed the installation to the letter.

Steps to reproduce:

screen -S Survival
cd /home/<user>/servers
mark2 start ./Survival
mark2 attach

Result: 

http://rev.ndev.me/xwn.png

**Comment by barneygale** [comment]
Hi,

Which SSH client are you using? If putty, please try changing your charset from latin-1 or ISO-whatever to UTF8 or UTF16.

**Comment by lwatsondev** [comment]
Yeah, using putty. Tried what you suggested and it still happens. I will try another SSH client and see if it still happens.

**Comment by barneygale** [comment]
Be sure to start a new screen too! Your old one may have a cached charset I suppose.

Do you have a particular reason you're running in a screen? mark2 provides some of the same functionality (e.g. ctrl-c when attached won't kill the server), and you can switch between servers in a similar way you would screens.

**Comment by lwatsondev** [comment]
OK, it /seems/ to be working now, aside from one little thing.

The Ctrl + Arrow key to switch servers doesn't seem to be working, despite them being listed in the wrapper.

http://grab.by/m81S

Any ideas?

**Comment by barneygale** [comment]
That character set still looks buggered. Run `echo $LANG` for me inside and outside the screen?

The ctrl+arrow thing I've heard not working in putty. Keyboard shortcuts will be configurable soon, but in the meantime you may have to ctrl-c out and `mark2 attach -n foo` to switch.

**Comment by edk0** [comment]
I'm closing this as it's been inactive for over 2 weeks now

**Comment by lwatsondev** [comment]
Oh, yeah. My bad. 

Issue resolved, it was a putty issue.
