### ISSUE TITLE
permissions and the Twisted plugin cache

### ISSUE THREAD

**Issue by edk0** [barneygale/mark2#67]
starting mark2 when it hasn't been started before yields a permission error because Twisted hasn't generated its plugin cache in .../twisted/plugins/. there are two ways round this I can see:
- Make twisted/plugins world-writable by default. I'm strongly against this. config/ is bad enough. twisted/plugins actually contains python source code that is executed.
- Add a `mark2 install` command, and make config/ and twisted/plugins 755. install commands are nasty, but I can't see a way round this one that doesn't have security problems.

**Comment by barneygale** [comment]
does twistd's `--no-save` affect it?

**Comment by barneygale** [comment]
Apparently not.
