### ISSUE TITLE
"Read timed out" restarting not working

### ISSUE THREAD

**Issue by vemacs** [barneygale/mark2#68]
I currently don't have the log at the moment (/tmp/mark2 is somewhat empty), but as I run a FTB server, it's erm well, unstable.

Mark2 is detecting that the server has frozen (it is still accepting connections via query, but it mentions that a crash has been detected), something similar to:

```
Read timed out
Crash detected: restarting in -1 minutes
```

However, it doesn't restart. Instead, all it does is loop:

```
Read timed out
Crash detected: restarting in -2 minutes
Read timed out
Crash detected: restarting in -3 minutes
```

And so on. It never actually restarts, it just decreases the negative number by one.

I wish I would have the log, but strangely, it got wiped. Do you mind looking at the logic for this particular crash check?

Thanks. FTB is kinda unstable

_Note: The server does restart cleanly (e.g. with map save) with `~restart`._

**Comment by edk0** [comment]
Which version is your mark2? (output of `git log -1` in your mark2 directory)

I fixed [a typo that would have caused this](https://github.com/mcdevs/mark2/commit/1b27d61e1ece417c86c8b1af6b918ab2471707d1) 10 days ago.

**Comment by vemacs** [comment]
I just realized that I wgetted the package, but didn't extract it. Oops.
