### ISSUE TITLE
Remove mark2.properties requirement in /config

### ISSUE THREAD

**Issue by vemacs** [barneygale/mark2#76]
It makes updating with `wget` a pain, as I have to copy `resources/mark2.default.properties` to `config/mark2.properties` to start the server, and as I use a separate mark2.properties in my server folder, this isn't really needed and could seriously break upgrades.

Is it possible to deprecate this for forwards-compatibility and ease of installing/updating?

**Comment by barneygale** [comment]
Hey vemacs,

Your server should always inherit from resources/mark2.default.properties. Newer builds of mark2 will prompt you to edit this file on first then, then save _the difference_ to config/mark2.properties. You can happily leave config/mark2.properties blank.

In the past we copied resources/mark2.default.properties wholesale, but as you say this makes upgrading a massive pain.

**Comment by vemacs** [comment]
Cool, just noticed that.
