### ISSUE TITLE
Won't start due to syntax.

### ISSUE THREAD

**Issue by mjgerace** [barneygale/mark2#77]
Syntax error: http://pastebin.com/Y806J6eQ

**Comment by mjgerace** [comment]
Ahh nevermind, had to use the python27 prefix to get it to work. Sorry!

**Comment by vemacs** [comment]
Suggestion: Close the ticket.

**Comment by edk0** [comment]
this is a valid issue actually - mark2 is supposed to be compatible with python 2.6.

**Comment by edk0** [comment]
should be fixed in 06aa6e2
